#
#Makefile file for file test
#Author : yangbing
#

TARGET_TYPE = console
MODULE_NAME = fileTest

NEED_DTL = 1
#NEED_CPPUNIT = 1


#
#
#
#
VPATH = ./

#
#.cpp files to compile
#

ALL_CPP_FILES = ./fileTest.cpp
include $(DTSRC)/config.gcc
