#
# Makefile file for 
# Author: 
#

# Defines the basic path for current directory

NEED_DTL = 1

TARGET_TYPE = console
MODULE_NAME = tc_filestream

#
# 头文件目录
#


#
# 源代码路径, 必须使用 : 隔开, 不能有空格...
#
VPATH = ./

#
# 资源文件名称
#
#MO_RES_FILES = monitor.po
	
ALL_CPP_FILES = ./filestream.cpp	\
				./test.cpp

include $(DTSRC)/config.gcc