#
# Makefile file for DTL
# Author: hanxin
#

# Defines the basic path for current directory

TARGET_TYPE = console
MODULE_NAME = tc_security

NEED_DTL = 1
NEED_CPPUNIT = 1


#
# 源代码路径, 必须使用 : 隔开, 不能有空格...
#
VPATH = ./

ALL_CPP_FILES =	./base16tc.cpp	\
				./base64tc.cpp  \
				./rc4tc.cpp  \
				./rijndaeltc.cpp \
				./md5tc.cpp	\
				./sha1tc.cpp \
				./main.cpp	

include $(DTSRC)/config.gcc
