#
# Makefile file for testcase of libusermgm.so
# Author: 
#
NEED_DTL = 1


TARGET_TYPE = console
MODULE_NAME = tc_Mailtest



#
# 源代码路径, 必须使用 : 隔开, 不能有空格...
#
	
ALL_CPP_FILES = main.cpp				\
				mutilThread.cpp			\
				MutilThreadRead.cpp 	\
				MutilThreadWrite.cpp	\
				MutilThreadSendMail.cpp \
				strategy.cpp			\
				tcJson.cpp				\
				
		


include $(DTSRC)/config.gcc
