#
# Makefile file for DTL
# Author: hanxin
#

# Defines the basic path for current directory

TARGET_TYPE = console
MODULE_NAME = tc_test

NEED_DTL = 1
NEED_SYSTEM = 1
NEED_ZLIB = 1
NEED_POCO = 1
NEED_TCMALLOC = 1
#
# 头文件目录
#
CUSTOM_CXXFLAGS = 
CUSTOM_LIB_FLAGS = 


#  
# 源代码路径, 必须使用 : 隔开, 不能有空格...
#
VPATH = ./


#
# 自定义 ALL 参数
#

# All CPP files of
	
ALL_CPP_FILES =./tcEthernet.cpp

include $(DTSRC)/config.gcc

