#
# Makefile file for testcase of libusermgm.so
# Author: 
#
NEED_DTL = 1


TARGET_TYPE = console
MODULE_NAME = tc_Mail



#
# 源代码路径, 必须使用 : 隔开, 不能有空格...
#
	
ALL_CPP_FILES =	main.cpp   \
				
				
				
		


include $(DTSRC)/config.gcc
