#
# Makefile file for testcase of librijndael.so
# Author: sunzhuofeng
#
NEED_DTL = 1  

TARGET_TYPE = console
MODULE_NAME = test_Base64_1



CUSTOM_LIB_FLAGS = 

#
# 源代码路径, 必须使用 : 隔开, 不能有空格...
#
VPATH = ./:../
	
ALL_CPP_FILES = test_Base64_1.cpp



include $(DTSRC)/config.gcc