#
# Makefile file for testcase of libusermgm.so
# Author: Lyre
#
NEED_DTL = 1


TARGET_TYPE = console
MODULE_NAME = tc_thread



CUSTOM_LIB_FLAGS =

#
# 源代码路径, 必须使用 : 隔开, 不能有空格...
#
VPATH = ./:../:../../
	
ALL_CPP_FILES = main.cpp \
		tc_thread.cpp


include $(DTSRC)/config.gcc

