#
# Makefile file for testcase of libusermgm.so
# Author: 
#
NEED_DTL = 1


TARGET_TYPE = console
MODULE_NAME = tc_basefile



#
# 源代码路径, 必须使用 : 隔开, 不能有空格...
#
VPATH = ./:../
	
ALL_CPP_FILES = tcbasefile.cpp    


include $(DTSRC)/config.gcc
