#
# Makefile file for testcase of libusermgm.so
# Author: Lyre
#
NEED_DTL = 1


TARGET_TYPE = console
MODULE_NAME = tc_md5



CUSTOM_LIB_FLAGS =

#
# 源代码路径, 必须使用 : 隔开, 不能有空格...
#
VPATH = ./:../
	
ALL_CPP_FILES = tc_md5.cpp 


include $(DTSRC)/config.gcc
