#
# Makefile file for testcase of libusermgm.so
# Author: Lyre
#
NEED_DTL = 1
NEED_POCO = 1

TARGET_TYPE = console
MODULE_NAME = tc_http



CUSTOM_LIB_FLAGS =

#
# 源代码路径, 必须使用 : 隔开, 不能有空格...
#
VPATH = ./:../
	
ALL_CPP_FILES = main.cpp 


include $(DTSRC)/config.gcc
