/***************************************************************************************************
errorid.h:	
	C++ Foundation Library header files
	Copyright (c) Datatom Software, Inc.(2011)

Purpose:
	This file contain the declaration of error ID  

Author:
	韩欣 (han.xin@datatom.com)

Creating Time:
	2012-2-10
***************************************************************************************************/
#ifndef _DT_ERROR_ID_H_
#define _DT_ERROR_ID_H_

// 错误ID起初值
#define	EXP_BASE_ERROR_ID			0


// 共享管理	ID:0-50 
#define EXP_SHAREMGM_BASE_ID					(EXP_BASE_ERROR_ID + 50)

#define SHAREMGM_CREATE_DIR_FAILED				(EXP_BASE_ERROR_ID + 1)
#define SHAREMGM_REMOVE_DIR_FAILED				(EXP_BASE_ERROR_ID + 2)
#define SHAREMGM_LIST_FILE_FAILED				(EXP_BASE_ERROR_ID + 3)
#define SHAREMGM_GET_SAMBA_CONFIG_FAILED		(EXP_BASE_ERROR_ID + 4)
#define SHAREMGM_SETFACL_FAILED					(EXP_BASE_ERROR_ID + 5)
#define SHAREMGM_GETFACL_FAILED					(EXP_BASE_ERROR_ID + 6)
#define SHAREMGM_EDIT_SAMBA_CONFIG_FAILED		(EXP_BASE_ERROR_ID + 7)
#define SHAREMGM_RESTART_SMB_FAILED				(EXP_BASE_ERROR_ID + 8)
#define SHAREMGM_EDIT_NFS_CONFIG_FAILED			(EXP_BASE_ERROR_ID + 9)
#define SHAREMGM_VSFTPD_RESTART_FAILED			(EXP_BASE_ERROR_ID + 10)
#define SHAREMGM_EDIT_VSFTPD_CONFIG_FAILED		(EXP_BASE_ERROR_ID + 11)
#define SHAREMGM_RESTART_NFS_FAILED				(EXP_BASE_ERROR_ID + 12)
#define SHAREMGM_GET_VSFTPD_CONFIG_FAILED		(EXP_BASE_ERROR_ID + 13)
#define SHAREMGM_REMOVE_FTP_SHARE_FAILED		(EXP_BASE_ERROR_ID + 14)
#define SHAREMGM_DELFACL_FAILED					(EXP_BASE_ERROR_ID + 15)

// 文件过滤	ID:51-100 
#define EXP_SMBFILTER_BASE_ID					(EXP_SHAREMGM_BASE_ID + 50)

#define SMBFILTER_OPEN_DATABASE_FAILED			(EXP_SHAREMGM_BASE_ID + 1)
#define SMBFILTER_INSERT_TABLE_FAILED			(EXP_SHAREMGM_BASE_ID + 2)
#define SMBFILTER_DELETE_TABLE_FAILED			(EXP_SHAREMGM_BASE_ID + 3)
#define SMBFILTER_SELECT_TABLE_FAILED			(EXP_SHAREMGM_BASE_ID + 4)
#define SMBFILTER_CREATE_TABLE_FAILED			(EXP_SHAREMGM_BASE_ID + 5)


// 配额	ID:101-150 
#define EXP_QUOTAMGM_BASE_ID					(EXP_SMBFILTER_BASE_ID + 50)

#define QUOTA_OPEN_VOLUME_FAILED				(EXP_SMBFILTER_BASE_ID + 1)
#define QUOTA_EDIT_QUOTA_FAILED					(EXP_SMBFILTER_BASE_ID + 2)
#define QUOTA_QUERY_QUOTA_FAILED				(EXP_SMBFILTER_BASE_ID + 3)
#define QUOTA_GET_USER_LIST_FAILED				(EXP_SMBFILTER_BASE_ID + 4)
#define QUOTA_DISPLAY_WARING_FAILED				(EXP_SMBFILTER_BASE_ID + 5)
#define QUOTA_CLOSE_QUOTA_FAILED				(EXP_SMBFILTER_BASE_ID + 6)

// 目录操作	ID:151-200
#define EXP_DIROPERATE_BASE_ID					(EXP_QUOTAMGM_BASE_ID + 50)

#define DIROPERATE_CREATE_DIR_FAILED			(EXP_QUOTAMGM_BASE_ID + 1)
#define DIROPERATE_REMOVE_DIR_FAILED			(EXP_QUOTAMGM_BASE_ID + 2)
#define DIROPERATE_LIST_FILE_FAILED				(EXP_QUOTAMGM_BASE_ID + 3)
#define DIROPERATE_DIR_INVALID					(EXP_QUOTAMGM_BASE_ID + 4)
#define DIROPERATE_GET_SAMBA_CONFIG_FAILED		(EXP_QUOTAMGM_BASE_ID + 5)
#define DIROPERATE_GET_NFS_CONFIG_FAILED		(EXP_QUOTAMGM_BASE_ID + 6)
#define DIROPERATE_GET_FTP_CONFIG_FAILED		(EXP_QUOTAMGM_BASE_ID + 7)


// 目录同步 id: 201-250
#define EXP_RSYNC_BASE_ID 						(EXP_DIROPERATE_BASE_ID + 50)

#define OPEN_SQLITE_DB_FAILED					(EXP_DIROPERATE_BASE_ID + 1)
#define SOURCE_NAME_IS_NULL						(EXP_DIROPERATE_BASE_ID + 2)
#define SOURCE_PATH_IS_NULL						(EXP_DIROPERATE_BASE_ID + 3)
#define SOURCE_PATH_NOT_VALID					(EXP_DIROPERATE_BASE_ID + 4)
#define EXEC_SQLITE_FAILED						(EXP_DIROPERATE_BASE_ID + 5)
#define OPEN_FILE_FAILED						(EXP_DIROPERATE_BASE_ID + 6)
#define TASK_IS_NOTEXISTS						(EXP_DIROPERATE_BASE_ID + 7)
#define HAS_SAME_RSYNC_SOURCE					(EXP_DIROPERATE_BASE_ID + 8)
#define HAS_SAME_RSYNC_TASK						(EXP_DIROPERATE_BASE_ID + 9)



// 告警模块 id: 251- 300
#define EXP_ALARMCONFIG_BASE_ID 				(EXP_RSYNC_BASE_ID + 50)

#define ALARMCONFIG_OPEN_DATABASE_FAILED		(EXP_RSYNC_BASE_ID + 1)
#define ALARMCONFIG_QUERY_TABLE_FAILED			(EXP_RSYNC_BASE_ID + 2)
#define ALARMCONFIG_INSERT_TABLE_FAILED			(EXP_RSYNC_BASE_ID + 3)
#define ALARMCONFIG_SENDMAIL_FAILED				(EXP_RSYNC_BASE_ID + 4)
#define ALARMCONFIG_CREATE_TABLE_FAILED			(EXP_RSYNC_BASE_ID + 5)
#define ALARMCONFIG_DELETE_TABLE_FAILED			(EXP_RSYNC_BASE_ID + 6)
#define ALARMCONFIG_GET_TIME_FAILED				(EXP_RSYNC_BASE_ID + 7)
#define ALARMCONFIG_UPDATE_TABLE_FAILED			(EXP_RSYNC_BASE_ID + 8)
#define ALARMCONFIG_DELETE_MAILUSER_FAILED		(EXP_RSYNC_BASE_ID + 9)
#define ALARMCONFIG_DELETE_CLIENTUSER_FAILED	(EXP_RSYNC_BASE_ID + 10)


// SQLITE id: 301-350
#define EXP_SQLITE_BASE_ID 						(EXP_ALARMCONFIG_BASE_ID + 50)

#define SQLITE_OPEN_DB_FAILED					(EXP_ALARMCONFIG_BASE_ID + 1)
#define SQLITE_CLOSE_DB_FAILED					(EXP_ALARMCONFIG_BASE_ID + 2)
#define SQLITE_SEARCH_FAILED					(EXP_ALARMCONFIG_BASE_ID + 3)
#define SQLITE_INSERT_FAILED					(EXP_ALARMCONFIG_BASE_ID + 4)
#define SQLITE_UPDATE_FAILED					(EXP_ALARMCONFIG_BASE_ID + 5)
#define SQLITE_DELETE_FAILED					(EXP_ALARMCONFIG_BASE_ID + 6)
#define SQLITE_CREATE_TABLE_FAILED				(EXP_ALARMCONFIG_BASE_ID + 7)
#define SQLITE_DROP_TABLE_FAILED				(EXP_ALARMCONFIG_BASE_ID + 8)
#define SQLITE_VACCUM_DB_FAILED					(EXP_ALARMCONFIG_BASE_ID + 9)


// SQLITE id: 301-350
#define EXP_LICENSE_BASE_ID 					(EXP_SQLITE_BASE_ID + 50)

#define LICENSE_CODE_ILLEGAL					(EXP_SQLITE_BASE_ID + 1)
#define LICENSE_TYPE_ILLEGAL					(EXP_SQLITE_BASE_ID + 2)
#define LICENSE_NOT_EXIST						(EXP_SQLITE_BASE_ID + 3)
#define LICENSE_ALREADY_EXIST					(EXP_SQLITE_BASE_ID + 4)
#define LICENSE_ADD_TYPE_ERROR					(EXP_SQLITE_BASE_ID + 5)
#define LICENSE_KEY_ILLEGAL						(EXP_SQLITE_BASE_ID + 6)
#define LICENSE_NON_ACIVE_BASE					(EXP_SQLITE_BASE_ID + 7)
#define LICENSE_NOT_OFFICAL						(EXP_SQLITE_BASE_ID + 8)
#define LICENSE_ALREADY_ACTIVED					(EXP_SQLITE_BASE_ID + 9)
#define LICENSE_NO_SOME_AGENT_AUTH				(EXP_SQLITE_BASE_ID + 10)
#define LICENSE_GET_ETH_LIST_FAILED				(EXP_SQLITE_BASE_ID + 11)

// device manager id: 351-380
#define EXP_DEVICE_MANAGER_ID 					(EXP_LICENSE_BASE_ID + 30)

#define DEVICEMGM_MKFS_FAILED					(EXP_LICENSE_BASE_ID + 1)
#define DEVICEMGM_MOUNT_DEVICE_FAILED			(EXP_LICENSE_BASE_ID + 2)
#define DEVICEMGM_UMOUNT_DEVICE_FAILED			(EXP_LICENSE_BASE_ID + 3)

// disk manager id: 381-400
#define EXP_DISK_MANAGER_ID 					(EXP_DEVICE_MANAGER_ID + 20)

#define DISKMGM_GET_DISKLIST_FAILED				(EXP_DEVICE_MANAGER_ID + 1)
#define DISKMGM_RESCAN_FAILED					(EXP_DEVICE_MANAGER_ID + 2)
#define DISKMGM_GET_DISK_FAILED					(EXP_DEVICE_MANAGER_ID + 3)
#define DISKMGM_GET_DISK_NUM_FAILED				(EXP_DEVICE_MANAGER_ID + 4)

// disk manager id: 401-450
#define EXP_LVM_MANAGER_ID 						(EXP_DISK_MANAGER_ID + 50)

#define LVM_GET_DEVICE_FREE_SIZE_FAILED			(EXP_DISK_MANAGER_ID + 1)
#define LVM_VG_GET_VOLUME_LIST_FAILED			(EXP_DISK_MANAGER_ID + 2)
#define LVM_VG_GET_VOLUME_BYNAME_FAILED			(EXP_DISK_MANAGER_ID + 3)
#define LVM_VG_CHECKNAME_FAILED					(EXP_DISK_MANAGER_ID + 4)
#define LVM_VG_CREATE_FAILED					(EXP_DISK_MANAGER_ID + 5)
#define LVM_VG_DELETE_FAILED					(EXP_DISK_MANAGER_ID + 6)
#define LVM_VG_EXTEND_FAILED					(EXP_DISK_MANAGER_ID + 7)
#define LVM_VG_REDUCE_FAILED					(EXP_DISK_MANAGER_ID + 8)
#define LVM_VG_GET_GROUPLIST_FAILED				(EXP_DISK_MANAGER_ID + 9)
#define LVM_VG_GET_GROUPBYNAME_FAILED			(EXP_DISK_MANAGER_ID + 10)
#define LVM_PV_GET_VOLUME_LIST_FAILED			(EXP_DISK_MANAGER_ID + 11)
#define LVM_PV_GET_VOLUME_BYNAME_FAILED			(EXP_DISK_MANAGER_ID + 12)
#define LVM_PV_CHECKNAME_FAILED					(EXP_DISK_MANAGER_ID + 13)
#define LVM_PV_CREATE_FAILED					(EXP_DISK_MANAGER_ID + 14)
#define LVM_PV_DETETE_FAILED					(EXP_DISK_MANAGER_ID + 15)
#define LVM_PV_EXTEND_FAILED					(EXP_DISK_MANAGER_ID + 16)
#define LVM_PV_REDUCE_FAILED					(EXP_DISK_MANAGER_ID + 17)
#define LVM_PV_GET_GROUPLIST_FAILED				(EXP_DISK_MANAGER_ID + 18)
#define LVM_PV_GET_GROUPBYNAME_FAILED			(EXP_DISK_MANAGER_ID + 19)
#define LVM_PV_DELETE_FAILED					(EXP_DISK_MANAGER_ID + 20)
#define LVM_LV_CREATE_FAILED					(EXP_DISK_MANAGER_ID + 21)
#define LVM_LV_DELETE_FAILED					(EXP_DISK_MANAGER_ID + 22)
#define LVM_LV_EXTEND_FAILED					(EXP_DISK_MANAGER_ID + 23)
#define LVM_LV_REDUCE_FAILED					(EXP_DISK_MANAGER_ID + 24)
#define LVM_LV_GETVOLUME_LIST_FAILED			(EXP_DISK_MANAGER_ID + 25)
#define LVM_LV_DELETE_FAILED_ONLINE				(EXP_DISK_MANAGER_ID + 26)
#define LVM_LV_DELETE_FAILED_INACTIVE			(EXP_DISK_MANAGER_ID + 27)
#define LVM_GET_LV_INFO_FAILED					(EXP_DISK_MANAGER_ID + 28)
#define LVM_GET_PV_INFO_FAILED					(EXP_DISK_MANAGER_ID + 29)
#define LVM_GET_VG_INFO_FAILED					(EXP_DISK_MANAGER_ID + 30)
#define LVM_CREATE_LV_TOO_SMALL					(EXP_DISK_MANAGER_ID + 30)


// disk manager id: 401-450
#define EXP_RAID_MANAGER_ID 					(EXP_LVM_MANAGER_ID + 50)

#define RAIDMGM_GET_RAID_LIST_FAILED			(EXP_LVM_MANAGER_ID + 1)
#define RAIDMGM_GET_INDEX_BYID_FAILED			(EXP_LVM_MANAGER_ID + 2)
#define RAIDMGM_GET_RAIDNAME_BY_DISK_FAILED		(EXP_LVM_MANAGER_ID + 3)
#define RAIDMGM_CHECK_RAID_ID_FAILED			(EXP_LVM_MANAGER_ID + 4)
#define RAIDMGM_GET_RAID_BYID_FAILED			(EXP_LVM_MANAGER_ID + 5)
#define RAIDMGM_GET_RAID_BYNAME_FAILED			(EXP_LVM_MANAGER_ID + 6)
#define RAIDMGM_CREATE_RAID_FAILED				(EXP_LVM_MANAGER_ID + 7)
#define RAIDMGM_DELETE_RAID_FAILED				(EXP_LVM_MANAGER_ID + 8)
#define RAIDMGM_ENABLE_READ_CACHE_FAILED		(EXP_LVM_MANAGER_ID + 9)
#define RAIDMGM_DISABLE_READ_CACHE_FAILED		(EXP_LVM_MANAGER_ID + 10)
#define RAIDMGM_ENABLE_WRITE_CACHE_FAILED		(EXP_LVM_MANAGER_ID + 11)
#define RAIDMGM_DISABLE_WRITE_CACHE_FAILED		(EXP_LVM_MANAGER_ID + 12)
#define RAIDMGM_EXPAND_RAID_FAILED				(EXP_LVM_MANAGER_ID + 13)
#define RAIDMGM_ADDSPARE_DISK_FAILED			(EXP_LVM_MANAGER_ID + 14)
#define RAIDMGM_DELETESPARE_DISK_FAILED			(EXP_LVM_MANAGER_ID + 15)
#define RAIDMGM_ADD_GLOBAL_SPARE_DISK_FAILED	(EXP_LVM_MANAGER_ID + 16)

#define RAIDMGM_DELETE_GLOBAL_SPARE_DISK_FAILED	(EXP_LVM_MANAGER_ID + 17)
#define RAIDMGM_ENABLE_SOUND_ALARM_FAILED		(EXP_LVM_MANAGER_ID + 18)
#define RAIDMGM_DISABLE_SOUND_ALARM_FAILED		(EXP_LVM_MANAGER_ID + 19)
#define RAIDMGM_GETSTATUS_FAILED				(EXP_LVM_MANAGER_ID + 20)


// log manager id: 451-500
#define EXP_LOG_MANAGER_ID 						(EXP_RAID_MANAGER_ID + 50)

#define LOG_SEARCH_OPTION_ERROR					(EXP_RAID_MANAGER_ID + 1)
#define LOG_DELETE_OPTION_ERROR					(EXP_RAID_MANAGER_ID + 2)
#define LOG_OPEN_CRON_FILE_FAILED				(EXP_RAID_MANAGER_ID + 3)
#define LOG_PARA_ILLEGAL						(EXP_RAID_MANAGER_ID + 4)


// systemset id 501~550
#define SYSTEM_SET_ID							(EXP_LOG_MANAGER_ID+50)


// filesearch id 551~600
#define EXP_FILE_SEARCH_MANAGER_ID				(SYSTEM_SET_ID+50)

#define FILESEARCH_OPEN_DATABASE_FAILED			(SYSTEM_SET_ID+1)
#define INITIALIZE_INOTIFYTOOLS_FAILED			(SYSTEM_SET_ID+2)
#define INOTIFYTOOLS_SPRINTF_FAILED				(SYSTEM_SET_ID+3)
#define INOTIFYTOOLS_INSERT_DATABASE_FAILED		(SYSTEM_SET_ID+4)
#define INOTIFYTOOLS_DELETE_DATABASE_FAILED		(SYSTEM_SET_ID+5)
#define INOTIFYTOOLS_SELECT_DATABASE_FAILED		(SYSTEM_SET_ID+6)
#define INOTIFYTOOLS_CREATE_DATABASE_FAILED		(SYSTEM_SET_ID+7)
#define FILESEARCH_UPDATE_LOCATE_DB_FAILED		(SYSTEM_SET_ID+8)
#define FILESEARCH_EXECUTE_LOCATE_FAILED		(SYSTEM_SET_ID+9)

// iomonitor id 601~650
#define EXP_IO_MONITOR_BASE_ID					(EXP_FILE_SEARCH_MANAGER_ID+50)

#define VMSTAT_PROCCESS_START_FAILED			(EXP_FILE_SEARCH_MANAGER_ID+1)
#define PARAM_ARGUMENT_IS_NULL					(EXP_FILE_SEARCH_MANAGER_ID+2)

//user 651~700
#define EXP_USER_ID										(EXP_IO_MONITOR_BASE_ID+50)

//webdav 701~750
#define EXP_WEBDAV_ID								(EXP_USER_ID+50)

#define WEBDAVMGM_EDIT_WEBDAV_CONFIG_FAILED			(EXP_USER_ID+1)
#define WEBDAVMGM_STOP_APACHE_FAILED				(EXP_USER_ID+2)
#define WEBDAVMGM_START_APACHE_FAILED				(EXP_USER_ID+3)
#define WEBDAVMGM_OPEN_WEBDAV_PASSWD_FAILED			(EXP_USER_ID+4)
#define WEBDAVMGM_CHANGE_WEBDAV_PASSWD_FAILED		(EXP_USER_ID+5)

// iscsi 751~800
#define	EXP_ISCSI_ID								(EXP_WEBDAV_ID+50)

#define ISCSI_GET_CONF_FAIL							(EXP_WEBDAV_ID+1)


// idml 801 ~ 1000
#define EXP_IDML_ID									(EXP_ISCSI_ID + 50)

#define IDML_NO_THIS_FILE							(EXP_IDML_ID + 1)


#endif //_DT_ERROR_ID_H_

